apiVersion: v1
kind: Service
metadata:
  name: secure-service
  namespace: secure-app
spec:
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
